import { createMuiTheme } from '@material-ui/core/styles'

const contrastTheme = createMuiTheme({
  mainBackgroundColor: 'black',
  lightBackgroundColor: 'black',
  darkBackgroundColor: 'black',
  mainColor: 'black',
  mainColorCategoryEducation: 'black',
  mainColorCategoryNeighbour: 'black',
  mainColorCategoryHospitals: 'black',
  mainColorCategoryBusinesses: 'black',
  toolbarMainColor: 'yellow',
  toolbarMainColorCategoryEducation: 'yellow',
  toolbarMainColorCategoryNeighbour: 'yellow',
  toolbarMainColorCategoryHospitals: 'yellow',
  toolbarMainColorCategoryBusinesses: 'yellow',
  textMainColorCategoryEducation: 'yellow',
  textMainColorCategoryNeighbour: 'yellow',
  textMainColorCategoryHospitals: 'yellow',
  textMainColorCategoryBusinesses: 'yellow',
  fontColorLight: 'yellow',
  fontColorNormal: 'yellow',
  fontColorMedium: 'yellow',
  fontColorDark: 'yellow',
  fontColorUpvotesCount: 'yellow',
  blueActiveColor: 'yellow',
  blueActiveColorDark: 'yellow',
  modalColorLight: 'yellow',
  modalColorDark: 'yellow',
  modalColorVeryLight: 'yellow',
  resourceTileLayoutColor: 'yellow',
  footerColor: 'yellow',
  linkHoverLightColor: 'yellow',
  warningColor: 'yellow',
  tagColor: '#FFFF00',
  resourceTilesWidth: '920px',
  mobileResourceTilesWidth: '93%',
  headerContentWidth: 'calc(920px + 5%)',
  mobileHeaderContentWidth: '93%',
  minSiteWidth: '380px',
  shadowSmall: '0 4px 12px 0 rgba(0, 0, 0, 0.05)',
  shadowNormal: '3px 5px 10px -5px rgba(148, 148, 148, 1)',
  shadowButtonHover: '0px 0px 7px rgba(50, 50, 50, 0.2)',
  inputActiveBorder: '1px solid yellow',
  toolbarHeight: '4rem',
  footerHeight: '4rem',
  personTileWidth: '130px',
  buttonTransition: 'all 0.2s',
  borderRadiusSmall: '5px',
  borderRadiusMedium: '8px',
  borderRadiusBig: '30px',
  iconBackground: '#FFFF00',
  visibleIllustration: 'hidden',
  arrowBackColor: '#FFFF00',
  voteButtonTextColor: '#FFFF00',
  inputTextColor: 'yellow',
  inputBackgroundColor: 'black',
  inputBorder: '0.5px solid yellow',
  submitButtonBorder: true,
  submitButtonBackgroundColor: 'black',
  contrastSvgIcon: true,
  searchIconBorder: '1px solid yellow',
  paginationColor: 'primary',
  addInitiativeButtonBackgroundColor: '#000000',
  addInitiativeButtonBorderColor: '#FFFF00'
})

export default contrastTheme
