import { createMuiTheme } from '@material-ui/core/styles'

const theme = createMuiTheme({
  mainBackgroundColor: '#f9f9f9',
  lightBackgroundColor: '#fff',
  darkBackgroundColor: '#7f8fa4',
  mainColor: '#d8eaed',
  mainColorCategoryEducation: '#eddfe8',
  mainColorCategoryNeighbour: '#c4e3d4',
  mainColorCategoryHospitals: '#e1e9f7',
  mainColorCategoryBusinesses: '#eae0d3',
  toolbarMainColor: '#aacbcf',
  toolbarMainColorCategoryEducation: '#cfb4c5',
  toolbarMainColorCategoryNeighbour: '#79c9a9',
  toolbarMainColorCategoryHospitals: '#b1c2e0',
  toolbarMainColorCategoryBusinesses: '#d6c0a0',
  textMainColorCategoryNeighbour: '#2a915f',
  textMainColorCategoryHospitals: '#3e82fc',
  textMainColorCategoryBusinesses: '#f1a03c',
  fontColorLight: '#fff',
  fontColorNormal: '#b9c2cd',
  fontColorMedium: '#919191',
  fontColorDark: '#171717',
  fontColorUpvotesCount: '#7f8fa4',
  blueActiveColor: '#0091ff',
  blueActiveColorDark: '#005a9e',
  modalColorLight: '#62718a',
  modalColorDark: '#62718a',
  modalColorVeryLight: '#e6eaee',
  resourceTileLayoutColor: '#dee1e7',
  footerColor: '#dee1e7',
  linkHoverLightColor: '#b2bbc8',
  warningColor: '#ff0000',
  tagColor: '#219653',
  tagBackgroundColor: '#c4e3d4',
  resourceTilesWidth: '920px',
  mobileResourceTilesWidth: '93%',
  headerContentWidth: 'calc(920px + 5%)',
  mobileHeaderContentWidth: '93%',
  minSiteWidth: '380px',
  shadowSmall: '0 4px 12px 0 rgba(0, 0, 0, 0.05)',
  shadowNormal: '3px 5px 10px -5px rgba(148, 148, 148, 1)',
  shadowButtonHover: '0px 0px 7px rgba(50, 50, 50, 0.2)',
  inputActiveBorder: '1px solid #0091ff',
  toolbarHeight: '4rem',
  footerHeight: '4rem',
  personTileWidth: '130px',
  buttonTransition: 'all 0.2s',
  borderRadiusSmall: '5px',
  borderRadiusMedium: '8px',
  borderRadiusBig: '30px',
  iconBackground: 'transparent',
  visibleIllustration: 'visible',
  arrowBackColor: '#7f8fa4',
  voteButtonTextColor: '#969696',
  submitButtonBorder: false,
  inputTextColor: 'inherit',
  inputBackgroundColor: 'white',
  inputBorder: 'inherit',
  submitButtonBackgroundColor: '#0091ff',
  contrastSvgIcon: false,
  searchIconBorder: '1px solid #dee1e6',
  paginationColor: undefined,
  mainFontSize: '1rem',
  addInitiativeButtonBackgroundColor: '#fff',
  addInitiativeButtonBorderColor: '#000000'
})

export default theme
